# Generated by Django 5.0.6 on 2024-06-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('type1', models.CharField(choices=[('NORMAL', 'NORMAL'), ('FIRE', 'FIRE'), ('WATER', 'WATER'), ('GRASS', 'GRASS'), ('ELECTRIC', 'ELECTRIC'), ('ICE', 'ICE'), ('FIGHTING', 'FIGHTING'), ('POISON', 'POISON'), ('GROUND', 'GROUND'), ('FLYING', 'FLYING'), ('PSYCHIC', 'PSYCHIC'), ('BUG', 'BUG'), ('ROCK', 'ROCK'), ('GHOST', 'GHOST'), ('DRAGON', 'DRAGON'), ('DARK', 'DARK'), ('STEEL', 'STEEL'), ('FAIRY', 'FAIRY')], max_length=20)),
                ('type2', models.CharField(blank=True, choices=[('NORMAL', 'NORMAL'), ('FIRE', 'FIRE'), ('WATER', 'WATER'), ('GRASS', 'GRASS'), ('ELECTRIC', 'ELECTRIC'), ('ICE', 'ICE'), ('FIGHTING', 'FIGHTING'), ('POISON', 'POISON'), ('GROUND', 'GROUND'), ('FLYING', 'FLYING'), ('PSYCHIC', 'PSYCHIC'), ('BUG', 'BUG'), ('ROCK', 'ROCK'), ('GHOST', 'GHOST'), ('DRAGON', 'DRAGON'), ('DARK', 'DARK'), ('STEEL', 'STEEL'), ('FAIRY', 'FAIRY')], max_length=20, null=True)),
                ('images', models.TextField()),
                ('sprite', models.ImageField(upload_to='')),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('spattack', models.IntegerField()),
                ('spdefense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('total', models.IntegerField()),
                ('fourx', models.TextField(default='[]')),
                ('twox', models.TextField(default='[]')),
                ('onex', models.TextField(default='[]')),
                ('halfx', models.TextField(default='[]')),
                ('zerox', models.TextField(default='[]')),
            ],
        ),
    ]
